spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    #url: jdbc:mysql:///wechat_order?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC    使用高版本的mysql驱动会存在时区问题
    url: jdbc:mysql:///wechat_order?characterEncoding=utf-8&useSSL=false
#  jpa:
#    show-sql: true

mybatis:
  configuration:
      map-underscore-to-camel-case: true     #开启下划线转驼峰
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hnu.wechatorder.model

logging:
  level:
    com.hnu.wechatorder.dao: trace

server:                      #url前缀
  servlet:
    context-path: /sell


