spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#    url: jdbc:mysql:///wechat_order?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC    使用高版本的mysql驱动会存在时区问题
    url: jdbc:mysql:///wechat_order?characterEncoding=utf-8&useSSL=false
#  jackson:
#    default-property-inclusion: non_null
#  jpa:
#    show-sql: true
  jackson:
    default-property-inclusion: non_null

mybatis:
  configuration:
      map-underscore-to-camel-case: true     #开启下划线转驼峰
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hnu.wechatorder.model

logging:
  pattern:
    console: "%d - %msg%n"
#  path: /log/
  file: /log/sell.log
  level:
    com.hnu.wechatorder.dao: trace

server:                      #url前缀
  servlet:
    context-path: /sell


wechat:
  mpAppId: wxc1db73949ccdeda5
  mpAppSecret: 3f23472ffac3ff5859de597c0fae708d
  mchId: 1409146202
  mchKey: c97da54ddaqdwxxxxxxxxxxxxxxxxxx
  keyPath: E:/weixin_cert/h5.p12
  notifyUrl: http://sell.natpapp.cc/sell/pay/notify

